import {
  AlarmClock,
  BadgeCheck,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Brain,
  Building2,
  Calendar,
  CircleCheck,
  Clock,
  Code2,
  CreditCard,
  Database,
  FileSpreadsheet,
  FileText,
  Filter,
  Gauge,
  Globe,
  Handshake,
  Headphones,
  Heart,
  Image as ImageIcon,
  Inbox,
  Languages,
  Layers,
  LayoutTemplate,
  Link as LinkIcon,
  List,
  ListChecks,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  MousePointerClick,
  Phone,
  Plug,
  Rocket,
  Route,
  Search,
  Send,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Store,
  Tag,
  Target,
  Ticket,
  TrendingUp,
  Type,
  UserCheck,
  UserCog,
  UserX,
  Users,
  Video,
  Wand2,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { CmsIconName } from "@/lib/cms/icons";

/**
 * CMS icon names → lucide components.
 *
 * Typed as a complete record over CmsIconName, so an icon added to
 * lib/cms/icons.ts without a component here fails the build instead of rendering
 * nothing. No "use client": server sections render these directly, and client
 * sections receive the *name* across the boundary, never the component.
 */
export const CMS_ICONS: Record<CmsIconName, LucideIcon> = {
  MessageSquare,
  MessageCircle,
  MessagesSquare,
  Inbox,
  Send,
  Bot,
  Brain,
  Sparkles,
  Wand2,
  Zap,
  Target,
  Gauge,
  TrendingUp,
  BarChart3,
  Users,
  UserCheck,
  UserCog,
  UserX,
  Workflow,
  Route,
  BookOpen,
  Megaphone,
  Ticket,
  ShieldCheck,
  BadgeCheck,
  CircleCheck,
  ListChecks,
  Clock,
  AlarmClock,
  Bell,
  FileText,
  FileSpreadsheet,
  Image: ImageIcon,
  Video,
  Mic,
  MapPin,
  List,
  MousePointerClick,
  LayoutTemplate,
  Type,
  Link: LinkIcon,
  Webhook,
  Code2,
  Plug,
  Database,
  Mail,
  Phone,
  Globe,
  Languages,
  Lock,
  Heart,
  Star,
  Smile,
  Rocket,
  Building2,
  Store,
  CreditCard,
  Calendar,
  Search,
  Filter,
  Tag,
  Layers,
  Handshake,
  Headphones,
};

export function CmsIcon({ name, className }: { name: string; className?: string }) {
  const Icon = CMS_ICONS[name as CmsIconName] ?? Sparkles;
  return <Icon aria-hidden className={className} />;
}
